### PR TITLE
SAF

### LINKED ISSUE #190: File permissions
Even though we can safely copy off data files from the shared documents location, we can't edit the ones we read in (input data).  If we try to overwrite the file, when we run the app, it crashes (permission issue).  Even if we catch the exception we still can't read it.   I've been looking into SAF a bit, and there "text editor" apps that can read the files - during install, it asks if the app can have permissions ONCE and then it always works, even though that app didn't create the file.

SO IT'S POSSIBLE.  I just haven't figured out how yet.

Here's some snippets of code I was playing with.  This will ask the user for permission to the documents folder, but i guess it doesn't let you read files from there?  

    @Override
    public void onActivityResult(int requestCode, int resultCode,
                                 Intent resultData) {
        super.onActivityResult(requestCode, resultCode, resultData);
        if (requestCode == 3663
                && resultCode == Activity.RESULT_OK) {
            Toast.makeText(AppLaunch.this, (CharSequence) "Thank You!", Toast.LENGTH_SHORT).show();
            // The result data contains a URI for the document or directory that
            // the user selected.
            Uri uri = null;
            if (resultData != null) {
                uri = resultData.getData();
                getContentResolver().takePersistableUriPermission(uri, Intent.FLAG_GRANT_READ_URI_PERMISSION | Intent.FLAG_GRANT_WRITE_URI_PERMISSION);
            }
        }
    }

    // Ask the user to allow permissions to the public/shared files.
    URI uri = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS).toURI();
    Uri uri2 = Uri.parse(uri.toString());

    // Check if we have permissions already.  since we're only asking for 1 permission, if the list
    // has anything in it (size > 0) then we're going to be okay.
    List<UriPermission> perm_list = getContentResolver().getPersistedUriPermissions();

    // If we don't have permissions, prompt the user to grant it.
        if (perm_list.isEmpty()) {
        // Choose a directory using the system's file picker.
        Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);
        intent.putExtra(DocumentsContract.EXTRA_INITIAL_URI, uri);
        startActivityForResult(intent, 3663);
    }

### PR DESCRIPTION
**Pull request by Jeff-Stammler**
fixes #190

### CODE REVIEW

File: app/src/main/java/com/team3663/scouting_app/utility/Logger.java [hunk 1]
```diff
@@ -56,74 +53,58 @@ public void clear() {
...
-        File file_data = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS), filename_data);
-        File file_event = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS), filename_event);
-
-        // Ensure the directory structure exists first - only need to check with one file
-        if (!Objects.requireNonNull(file_data.getParentFile()).exists()) {
-            rc = Objects.requireNonNull(file_data.getParentFile()).mkdirs();
-            if (!rc) Toast.makeText(appContext, "Failed to create directory: " + file_data.getParentFile().getName(), Toast.LENGTH_LONG).show();
-        }
+        String filename_data = Globals.CurrentCompetitionId + "_" + Globals.CurrentMatchNumber + "_" + Globals.CurrentDeviceId + "_d.csv";
+        String filename_event = Globals.CurrentCompetitionId + "_" + Globals.CurrentMatchNumber + "_" + Globals.CurrentDeviceId + "_e.csv";
```
Comment (AdrielStammler) [inline app/src/main/java/com/team3663/scouting_app/utility/Logger.java:61]: Not super important, but this feels very inefficient cause they are the same except for the `_d` and `_e`.

File: app/src/main/java/com/team3663/scouting_app/utility/Logger.java [hunk 2]
```diff
@@ -200,6 +167,7 @@ private void WriteOutDataFile(File in_File_Data) {
 
         try {
             // Write out the data
+            assert fos_data != null;
```
Comment (AdrielStammler) [inline app/src/main/java/com/team3663/scouting_app/utility/Logger.java:170]: What does `assert` do?

File: app/src/main/java/com/team3663/scouting_app/activities/AppLaunch.java [hunk 3]
```diff
@@ -44,21 +47,33 @@ protected void onActivityResult(int in_requestCode, int in_resultCode, Intent in
...
+                            LoadDataFile(getString(R.string.file_matches), getString(R.string.applaunch_loading_matches), getString(R.string.applaunch_file_error_matches));
+                            Thread.sleep(Constants.AppLaunch.SPLASH_SCREEN_DELAY);
+                            appLaunchBinding.textStatus.setText("");
+                        } catch (InterruptedException e) {
+                            throw new RuntimeException(e);
+                        }
                     }
-                }
+                    break;
+                case Constants.AppLaunch.ACTIVITY_CODE_STORAGE:
```
[the remark this answers is not in the document]
Comment (Jeff-Stammler) [reply app/src/main/java/com/team3663/scouting_app/activities/AppLaunch.java:66]: it's the same thing.  In order to ask for permission to use the Documents folder, you call an intent with result.  That intent is not an activity per se, but build into the SAF, and it prompts the user to select a folder.  Then it comes back to our app and this tells us we came back from asking for storage access, just like we come back from settings.

File: app/src/main/java/com/team3663/scouting_app/activities/AppLaunch.java [hunk 4]
```diff
@@ -44,21 +47,33 @@ protected void onActivityResult(int in_requestCode, int in_resultCode, Intent in
...
+                    Uri treeUri = in_data.getData();
```
[the remark this answers is not in the document]
Comment (Jeff-Stammler) [reply app/src/main/java/com/team3663/scouting_app/activities/AppLaunch.java:67]: URI: Uniform Resource Identifier (URI) is a string of characters used to identify a name or a resource on the Internet.

it's built into Java and it contains a path formatted in a special way to point to the folder.  It's just what it needed to use, so i used it.  :)

File: app/src/main/java/com/team3663/scouting_app/activities/AppLaunch.java [hunk 5]
```diff
@@ -162,19 +217,16 @@ public void run() {
...
+                    appLaunchBinding.butStartScouting.setVisibility(View.VISIBLE);
+                    appLaunchBinding.imgButSettings.setVisibility(View.VISIBLE);
+                    appLaunchBinding.butStartScouting.setClickable(true);
+                    appLaunchBinding.imgButSettings.setClickable(true);
+                    appLaunchBinding.butStartScouting.setVisibility(View.VISIBLE);
+                    appLaunchBinding.imgButSettings.setVisibility(View.VISIBLE);
                 });
             }
-        }, 100);
+        }, 10);
```
[the remark this answers is not in the document]
Comment (Jeff-Stammler) [reply app/src/main/java/com/team3663/scouting_app/activities/AppLaunch.java:229]: Maybe no, but YOU will never notice those extra 9 milliseconds.  lol.  I DID want to make sure it ran after everything else was done.  I figured shaving 90 milliseconds was good enough.

File: app/src/main/java/com/team3663/scouting_app/activities/AppLaunch.java [hunk 6]
```diff
@@ -321,7 +372,7 @@ else if (in_fileName.equals(getString(R.string.file_trap_results))) {
                         Globals.TrapResultsList.addTrapResultRow(info[0], info[2]);
                 }
             }
-        } catch (IOException e) {
+        } catch (IOException  e) {
```
[the remark this answers is not in the document]
Comment (Jeff-Stammler) [reply app/src/main/java/com/team3663/scouting_app/activities/AppLaunch.java:375]: Oh, during development, there was a 2nd exception i needed to capture.  Later i didn't need it, so i removed the 2nd one, but it left an extra space.  This isn't needed and could be cleaned up.

File: app/src/main/java/com/team3663/scouting_app/activities/Match.java [hunk 7]
```diff
@@ -642,7 +628,7 @@ private void initNotMoving() {
             } else {
                 Globals.EventLogger.LogEvent(Constants.Events.ID_NOT_MOVING_END, 0,0,false);
                 matchBinding.switchNotMoving.setBackgroundColor(Constants.Match.BUTTON_COLOR_NORMAL);
-                Achievements.data_IdleTime += System.currentTimeMillis() - starttime_not_moving;
+                Achievements.data_IdleTime += (int)(System.currentTimeMillis() - starttime_not_moving);
```
[the remark this answers is not in the document]
Comment (Jeff-Stammler) [reply app/src/main/java/com/team3663/scouting_app/activities/Match.java:631]: there was a compiler WARNING that we're implicitly converting from long to int.  By making an explicit casting, the warning went away.  I acknowledge the long->int lossy-ness but since we're subtracting two longs, it'll fit into an int.  :)

File: app/src/main/java/com/team3663/scouting_app/utility/Logger.java (hunk 1 above)
Comment (Jeff-Stammler) [reply app/src/main/java/com/team3663/scouting_app/utility/Logger.java:61]: any suggestions?

File: app/src/main/java/com/team3663/scouting_app/utility/Logger.java (hunk 2 above)
Comment (Jeff-Stammler) [reply app/src/main/java/com/team3663/scouting_app/utility/Logger.java:170]: it short for "assertion".  I'm "asserting" that this is true (fos_data != null).  If it's not true, the app will crash with an error that the assertion wasn't true.  It's a common way to "prove" something is true that should always be true.  I added it to avoid a compiler warning and to avoid having to write an if block around it.  the way the code is written, it really won't be null here, so using assert should be fine.

File: app/src/main/java/com/team3663/scouting_app/utility/Logger.java (hunk 1 above)
Comment (AdrielStammler) [reply app/src/main/java/com/team3663/scouting_app/utility/Logger.java:61]: Have one variable that is everything but the `_d.csv` or `_e.csv` then just add that in when you use it.

File: app/src/main/java/com/team3663/scouting_app/utility/Logger.java (hunk 2 above)
Comment (AdrielStammler) [reply app/src/main/java/com/team3663/scouting_app/utility/Logger.java:170]: I knew what it stood for I just was confused about what it could do if it wasn't true. The app crashing doesn't sound great.

File: app/src/main/java/com/team3663/scouting_app/activities/AppLaunch.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (AdrielStammler) [reply app/src/main/java/com/team3663/scouting_app/activities/AppLaunch.java:229]: OK fair enough

File: app/src/main/java/com/team3663/scouting_app/utility/Logger.java (hunk 1 above)
Comment (Jeff-Stammler) [reply app/src/main/java/com/team3663/scouting_app/utility/Logger.java:61]: Sure, but then when I use it, there's more calculations.  I DO like this since HOW we name it is contained to these lines (in case we change it later).

File: app/src/main/java/com/team3663/scouting_app/utility/Logger.java (hunk 2 above)
Comment (Jeff-Stammler) [reply app/src/main/java/com/team3663/scouting_app/utility/Logger.java:170]: the app would have crashed if we used it as a null anyways.
also, it's what Android Studio suggested to do to avoid the warning.

File: app/src/main/java/com/team3663/scouting_app/activities/AppLaunch.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (AdrielStammler) [reply app/src/main/java/com/team3663/scouting_app/activities/AppLaunch.java:66]: OK. `Storage` wasn't very clear. And I didn't know it worked like that.

File: app/src/main/java/com/team3663/scouting_app/utility/Logger.java (hunk 2 above)
Comment (Jeff-Stammler) [reply app/src/main/java/com/team3663/scouting_app/utility/Logger.java:170]: like i said, it's not null at this point.  so it's more about not having the warning.  i don't know what java does, but it might be an assert/crash only when running it in debug mode.  (there are things like debug asserts, but i don't know about this one.

File: app/src/main/java/com/team3663/scouting_app/utility/Logger.java (hunk 1 above)
Comment (AdrielStammler) [reply app/src/main/java/com/team3663/scouting_app/utility/Logger.java:61]: I think it is fine. It just bothered my slightly, seeing it.

**Review by AdrielStammler — APPROVED** [review]

**Review by EllaNorby — APPROVED** [review]
